- name: Install PHP and necessary extensions
  apt:
    name:
      - php
      - php-cli
      - php-zip
      - php-mbstring
      - php-xml
      - php-curl
    state: present

- name: Download Composer installer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-setup.php

- name: Install Composer globally
  command: php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer  # Skip this task if Composer is already installed

- name: Clean up Composer installer
  file:
    path: /tmp/composer-setup.php
    state: absent