# Config for SSH
ssh_username: <ssh-username>
ssh_password: <ssh-password>
ssh_pubkey: <ssh-public-key>
# Config for Database Virtual machine
database:
  vm_ip: "192.168.33.21"
  vm_name: "vnlab_database"
  vm_port_forwarding:
    - guest: 5432
      host: 5432

  postgres_db: <database>
  postgres_username: <pg_username>
  postgres_password: <pg_password>

# Config for Server Virtual machine
server:
  vm_ip: "192.168.33.22"
  vm_name: "vnlab_server"
  vm_port_forwarding:
    - guest: 80
      host: 80
  
  domains:
    - frontend: 'y2aa-frontend.test'
    - backend:  'y2aa-backend.test'

  # Allow IP to connect to your server
  allow_ips:
    - '192.168.33.1'
    # Container subnet of your project
    - '172.28.0.0/16'
    # - 'all' # Allow all IPs